[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.gtk3]
input_path = '~/.templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = '~/.templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.waybar]
input_path = '~/.templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar && waybar &'

[templates.dunst]
input_path = '~/.templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'pkill dunst'

[templates.kitty]
input_path = '~/.templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.vesktop]
input_path = '~/.templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.spicetify]
input_path = '~/.templates/colors.ini'
output_path = '~/.config/spicetify/Themes/ziro/color.ini'
post_hook = 'spicetify apply'
